# DOCKER
spring.datasource.url=jdbc:mysql://db:3306/richkware
spring.datasource.username=${DB_USERNAME:richk}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.jpa.hibernate.ddl-auto=update

# Run the app on 8080 inside the container so Docker port mapping works
server.port=8080
